// languages.js
const translations = {
    en: {
        // Header
        title: "Home Cocktail Bar | Mix & Sip",
        logo: "🍸 Home Cocktail Bar",
        tagline: "Mix. Sip. Enjoy.",
        menuToggle: "Menu",
        
        // Navigation
        navCocktails: "Cocktails",
        navOrder: "Order",
        navAdmin: "Admin",
        
        // Hero Section
        heroTitle: "Discover Amazing Cocktails",
        heroText: "Tap cards to reveal recipes, order favorites, and become a home mixologist!",
        browseDrinks: "Browse Drinks",
        orderNow: "Order Now",
        
        // Cocktails Section
        cocktailsTitle: "Signature Cocktails",
        flipHint: "Tap to see recipe",
        flipBackHint: "Tap to flip back",
        
        // Recipe Card Back
        recipeTitle: "Recipe",
        instructions: "Instructions:",
        
        // Cocktail Names and Descriptions (Your new cocktails)
        "Strawberry Banana Cream": "Strawberry Banana Cream",
        "Strawberry Banana Cream Tag": "Creamy • Tropical • Sweet",
        "Blue Pineapple Lagoon": "Blue Pineapple Lagoon",
        "Blue Pineapple Lagoon Tag": "Tropical • Electric • Refreshing",
        "Malibu Sunset": "Malibu Sunset",
        "Malibu Sunset Tag": "Sweet • Tropical • Smooth",
        "Mango Guava Vodka Smash": "Mango Guava Vodka Smash",
        "Mango Guava Vodka Smash Tag": "Fresh • Juicy • Tropical",
        "Green Apple Fizz": "Green Apple Fizz",
        "Green Apple Fizz Tag": "Fresh • Fizzy • Aesthetic",
        "Purple Galaxy": "Purple Galaxy",
        "Purple Galaxy Tag": "Sweet • Smooth • Vibrant",
        "Watermelon Mojito Remix": "Watermelon Mojito Remix",
        "Watermelon Mojito Remix Tag": "Refreshing • Fruity • Light",
        "Frozen Party Slush": "Frozen Party Slush",
        "Frozen Party Slush Tag": "Big Batch • Fun • Slushy",
        "Margarita": "Margarita",
        "Margarita Tag": "Zesty • Salty • Classic",
        "Coca-Cola & Rum": "Coca-Cola & Rum",
        "Coca-Cola & Rum Tag": "Classic • Simple • Timeless",
        "Куманёк": "Kumanyok",
        "Куманёк Tag": "Bold • Rustic • Funny",
        "Rum Punch": "Rum Punch",
        "Rum Punch Tag": "Fruity • Tropical • Party",
        "Bloody Mary": "Bloody Mary",
        "Bloody Mary Tag": "Savory • Spicy • Classic",
        "Coffee": "Coffee",
        "Coffee Tag": "Hot • Simple • Energizing",
        "Tea": "Tea",
        "Tea Tag": "Hot • Calm • Classic",
        "Juice": "Juice",
        "Juice Tag": "Fresh • Non-Alcoholic • Choice",
        
        // Ingredients
        "Vodka": "Vodka",
        "Banana": "Banana",
        "Strawberries": "Strawberries",
        "Piña Colada": "Piña Colada",
        "Ice": "Ice",
        "Pineapple Juice": "Pineapple Juice",
        "Blue Curaçao": "Blue Curaçao",
        "Ginger Ale": "Ginger Ale",
        "Malibu": "Malibu",
        "Orange Juice": "Orange Juice",
        "Strawberry Fanta": "Strawberry Fanta",
        "Mango Juice": "Mango Juice",
        "Guava Juice": "Guava Juice",
        "Fresh Lime Juice": "Fresh Lime Juice",
        "Green Apple": "Green Apple",
        "Apple Juice": "Apple Juice",
        "Grape Juice": "Grape Juice",
        "Blueberry Juice": "Blueberry Juice",
        "Cranberry Juice": "Cranberry Juice",
        "Watermelon Mojito (can)": "Watermelon Mojito (can)",
        "Piña Colada (can)": "Piña Colada (can)",
        "Tequila": "Tequila",
        "Triple Sec": "Triple Sec",
        "Agave Syrup": "Agave Syrup",
        "Salt": "Salt",
        "White or Dark Rum": "White or Dark Rum",
        "Coca-Cola": "Coca-Cola",
        "Lime": "Lime",
        "Light Beer": "Light Beer",
        "Rum": "Rum",
        "Tomato Juice": "Tomato Juice",
        "Lemon Juice": "Lemon Juice",
        "Salt & Pepper": "Salt & Pepper",
        "Coffee": "Coffee",
        "Sugar": "Sugar",
        "Milk": "Milk",
        "Tea Bag": "Tea Bag",
        "Hot Water": "Hot Water",
        "Sugar or Honey": "Sugar or Honey",
        "Available Juices": "Available Juices",
        
        // Amount descriptions
        "1 whole": "1 whole",
        "100g": "100g",
        "150ml": "150ml",
        "1 cup": "1 cup",
        "120ml": "120ml",
        "20ml": "20ml",
        "Optional top": "Optional top",
        "Top up": "Top up",
        "80ml": "80ml",
        "1/2, muddled": "1/2, muddled",
        "Splash": "Splash",
        "50ml": "50ml",
        "25ml": "25ml",
        "15ml": "15ml",
        "For rim": "For rim",
        "1 wedge (optional)": "1 wedge (optional)",
        "250ml": "250ml",
        "30ml": "30ml",
        "60ml": "60ml",
        "10ml": "10ml",
        "Pinch": "Pinch",
        "1 cup": "1 cup",
        "Optional": "Optional",
        "": "Choice",
        
        // Order Section
        orderTitle: "Order Your Cocktail",
        yourName: "Your Name",
        namePlaceholder: "Enter your name",
        chooseDrink: "Choose Your Drink",
        selectCocktail: "Select a cocktail",
        extraIngredients: "Extra Ingredients",
        extraAlcohol: "Extra Alcohol",
        moreIce: "More Ice",
        lessSugar: "Less Sugar",
        extraGarnish: "Extra Garnish",
        makeSpicy: "Make it Spicy",
        specialInstructions: "Special Instructions",
        instructionsPlaceholder: "Any special requests or allergies?",
        placeOrder: "Place Order",
        yourOrder: "Your Order",
        previewPlaceholder: "Select a drink to see preview",
        
        // Order Preview
        previewName: "Name:",
        previewDrink: "Drink:",
        previewExtras: "Extras:",
        previewNotes: "Notes:",
        guest: "Guest",
        
        // Admin Access
        barManager: "Bar Manager",
        adminText: "Access the admin panel to view all orders",
        goToAdmin: "Go to Admin Panel",
        adminNote: "Admin Password Required",
        
        // Success Modal
        orderSent: "Order Sent!",
        successMessage: "Your cocktail request has been sent to the bar manager.",
        continue: "Continue",
        
        // Footer
        copyright: "© 2026 Home Cocktail Bar",
        responsible: "For home use only. Drink responsibly.",
        
        // Language Switcher
        language: "Language",
        english: "English",
        russian: "Russian",
        french: "French",
        selectLanguage: "Select Language"
    },
    
    ru: {
        // Header
        title: "Домашний Коктейль-Бар | Mix & Sip",
        logo: "🍸 Домашний Коктейль-Бар",
        tagline: "Смешай. Отпей. Насладись.",
        menuToggle: "Меню",
        
        // Navigation
        navCocktails: "Коктейли",
        navOrder: "Заказ",
        navAdmin: "Админ",
        
        // Hero Section
        heroTitle: "Откройте Удивительные Коктейли",
        heroText: "Нажимайте на карточки, чтобы увидеть рецепты, заказывайте любимые напитки и станьте домашним барменом!",
        browseDrinks: "Смотреть Напитки",
        orderNow: "Заказать Сейчас",
        
        // Cocktails Section
        cocktailsTitle: "Фирменные Коктейли",
        flipHint: "Нажмите для рецепта",
        flipBackHint: "Нажмите чтобы вернуть",
        
        // Recipe Card Back
        recipeTitle: "Рецепт",
        instructions: "Инструкция:",
        
        // Cocktail Names and Descriptions
        "Strawberry Banana Cream": "Клубнично-Банановый Крем",
        "Strawberry Banana Cream Tag": "Сливочный • Тропический • Сладкий",
        "Blue Pineapple Lagoon": "Голубая Ананасовая Лагуна",
        "Blue Pineapple Lagoon Tag": "Тропический • Электрический • Освежающий",
        "Malibu Sunset": "Закат Малибу",
        "Malibu Sunset Tag": "Сладкий • Тропический • Мягкий",
        "Mango Guava Vodka Smash": "Манго-Гуава Водка Смэш",
        "Mango Guava Vodka Smash Tag": "Свежий • Сочный • Тропический",
        "Green Apple Fizz": "Зелёное Яблоко Физз",
        "Green Apple Fizz Tag": "Свежий • Игривый • Эстетичный",
        "Purple Galaxy": "Фиолетовая Галактика",
        "Purple Galaxy Tag": "Сладкий • Мягкий • Яркий",
        "Watermelon Mojito Remix": "Арбузный Мохито Ремикс",
        "Watermelon Mojito Remix Tag": "Освежающий • Фруктовый • Лёгкий",
        "Frozen Party Slush": "Замороженный Партийный Слаш",
        "Frozen Party Slush Tag": "Большая Порция • Веселье • Слаш",
        "Margarita": "Маргарита",
        "Margarita Tag": "Пикантный • Солёный • Классический",
        "Coca-Cola & Rum": "Кока-Кола & Ром",
        "Coca-Cola & Rum Tag": "Классический • Простой • Вечный",
        "Куманёк": "Куманёк",
        "Куманёк Tag": "Смелый • Деревенский • Забавный",
        "Rum Punch": "Ром Пунш",
        "Rum Punch Tag": "Фруктовый • Тропический • Вечеринка",
        "Bloody Mary": "Кровавая Мэри",
        "Bloody Mary Tag": "Пикантный • Острый • Классический",
        "Coffee": "Кофе",
        "Coffee Tag": "Горячий • Простой • Бодрящий",
        "Tea": "Чай",
        "Tea Tag": "Горячий • Спокойный • Классический",
        "Juice": "Сок",
        "Juice Tag": "Свежий • Безалкогольный • Выбор",
        
        // Ingredients
        "Vodka": "Водка",
        "Banana": "Банан",
        "Strawberries": "Клубника",
        "Piña Colada": "Пина Колада",
        "Ice": "Лёд",
        "Pineapple Juice": "Ананасовый сок",
        "Blue Curaçao": "Блю Кюрасао",
        "Ginger Ale": "Имбирный эль",
        "Malibu": "Малибу",
        "Orange Juice": "Апельсиновый сок",
        "Strawberry Fanta": "Клубничная Фанта",
        "Mango Juice": "Манговый сок",
        "Guava Juice": "Гуава сок",
        "Fresh Lime Juice": "Свежий сок лайма",
        "Green Apple": "Зелёное яблоко",
        "Apple Juice": "Яблочный сок",
        "Grape Juice": "Виноградный сок",
        "Blueberry Juice": "Черничный сок",
        "Cranberry Juice": "Клюквенный сок",
        "Watermelon Mojito (can)": "Арбузный мохито (банка)",
        "Piña Colada (can)": "Пина Колада (банка)",
        "Tequila": "Текила",
        "Triple Sec": "Трипл сек",
        "Agave Syrup": "Сироп агавы",
        "Salt": "Соль",
        "White or Dark Rum": "Белый или тёмный ром",
        "Coca-Cola": "Кока-Кола",
        "Lime": "Лайм",
        "Light Beer": "Светлое пиво",
        "Rum": "Ром",
        "Tomato Juice": "Томатный сок",
        "Lemon Juice": "Лимонный сок",
        "Salt & Pepper": "Соль и перец",
        "Coffee": "Кофе",
        "Sugar": "Сахар",
        "Milk": "Молоко",
        "Tea Bag": "Чайный пакетик",
        "Hot Water": "Горячая вода",
        "Sugar or Honey": "Сахар или мёд",
        "Available Juices": "Доступные соки",
        
        // Amount descriptions
        "1 whole": "1 целый",
        "100g": "100г",
        "150ml": "150мл",
        "1 cup": "1 чашка",
        "120ml": "120мл",
        "20ml": "20мл",
        "Optional top": "По желанию",
        "Top up": "Долить",
        "80ml": "80мл",
        "1/2, muddled": "1/2, раздавленный",
        "Splash": "Брызги",
        "50ml": "50мл",
        "25ml": "25мл",
        "15ml": "15мл",
        "For rim": "Для ободка",
        "1 wedge (optional)": "1 долька (по желанию)",
        "250ml": "250мл",
        "30ml": "30мл",
        "60ml": "60мл",
        "10ml": "10мл",
        "Pinch": "Щепотка",
        "1 cup": "1 чашка",
        "Optional": "По желанию",
        "": "Выбор",
        
        // Order Section
        orderTitle: "Закажите Ваш Коктейль",
        yourName: "Ваше Имя",
        namePlaceholder: "Введите ваше имя",
        chooseDrink: "Выберите Напиток",
        selectCocktail: "Выберите коктейль",
        extraIngredients: "Дополнительные Ингредиенты",
        extraAlcohol: "Дополнительный алкоголь",
        moreIce: "Больше льда",
        lessSugar: "Меньше сахара",
        extraGarnish: "Дополнительный гарнир",
        makeSpicy: "Сделать острым",
        specialInstructions: "Особые Указания",
        instructionsPlaceholder: "Особые пожелания или аллергии?",
        placeOrder: "Разместить Заказ",
        yourOrder: "Ваш Заказ",
        previewPlaceholder: "Выберите напиток для просмотра",
        
        // Order Preview
        previewName: "Имя:",
        previewDrink: "Напиток:",
        previewExtras: "Дополнения:",
        previewNotes: "Примечания:",
        guest: "Гость",
        
        // Admin Access
        barManager: "Менеджер Бара",
        adminText: "Перейдите в админ-панель для просмотра всех заказов",
        goToAdmin: "Перейти в Админ-панель",
        adminNote: "Требуется пароль администратора",
        
        // Success Modal
        orderSent: "Заказ Отправлен!",
        successMessage: "Ваш запрос на коктейль отправлен менеджеру бара.",
        continue: "Продолжить",
        
        // Footer
        copyright: "© 2026 Домашний Коктейль-Бар",
        responsible: "Только для домашнего использования. Пейте ответственно.",
        
        // Language Switcher
        language: "Язык",
        english: "Английский",
        russian: "Русский",
        french: "Французский",
        selectLanguage: "Выберите Язык"
    },
    
    fr: {
        // Header
        title: "Bar à Cocktails Maison | Mix & Sip",
        logo: "🍸 Bar à Cocktails Maison",
        tagline: "Mélangez. Sirotez. Savourez.",
        menuToggle: "Menu",
        
        // Navigation
        navCocktails: "Cocktails",
        navOrder: "Commande",
        navAdmin: "Admin",
        
        // Hero Section
        heroTitle: "Découvrez des Cocktails Incroyables",
        heroText: "Tapez sur les cartes pour révéler les recettes, commandez vos favoris et devenez un mixologiste à la maison!",
        browseDrinks: "Voir les Boissons",
        orderNow: "Commander Maintenant",
        
        // Cocktails Section
        cocktailsTitle: "Cocktails Signature",
        flipHint: "Appuyez pour la recette",
        flipBackHint: "Appuyez pour retourner",
        
        // Recipe Card Back
        recipeTitle: "Recette",
        instructions: "Instructions:",
        
        // Cocktail Names and Descriptions
        "Strawberry Banana Cream": "Crème Fraise-Banane",
        "Strawberry Banana Cream Tag": "Crémeux • Tropical • Sucré",
        "Blue Pineapple Lagoon": "Lagune Ananas Bleu",
        "Blue Pineapple Lagoon Tag": "Tropical • Électrique • Rafraîchissant",
        "Malibu Sunset": "Coucher de Soleil Malibu",
        "Malibu Sunset Tag": "Sucré • Tropical • Doux",
        "Mango Guava Vodka Smash": "Mangue Goyave Vodka Smash",
        "Mango Guava Vodka Smash Tag": "Frais • Juteux • Tropical",
        "Green Apple Fizz": "Pomme Verte Fizz",
        "Green Apple Fizz Tag": "Frais • Pétillant • Esthétique",
        "Purple Galaxy": "Galaxie Violette",
        "Purple Galaxy Tag": "Sucré • Doux • Vibrant",
        "Watermelon Mojito Remix": "Mojito Pastèque Remix",
        "Watermelon Mojito Remix Tag": "Rafraîchissant • Fruité • Léger",
        "Frozen Party Slush": "Slush de Fête Glacé",
        "Frozen Party Slush Tag": "Grande Quantité • Amusant • Slush",
        "Margarita": "Margarita",
        "Margarita Tag": "Zesté • Salé • Classique",
        "Coca-Cola & Rum": "Coca-Cola & Rhum",
        "Coca-Cola & Rum Tag": "Classique • Simple • Intemporel",
        "Куманёк": "Koumanok",
        "Куманёк Tag": "Audacieux • Rustique • Amusant",
        "Rum Punch": "Punch au Rhum",
        "Rum Punch Tag": "Fruité • Tropical • Fête",
        "Bloody Mary": "Bloody Mary",
        "Bloody Mary Tag": "Salé • Épicé • Classique",
        "Coffee": "Café",
        "Coffee Tag": "Chaud • Simple • Énergisant",
        "Tea": "Thé",
        "Tea Tag": "Chaud • Calme • Classique",
        "Juice": "Jus",
        "Juice Tag": "Frais • Non-Alcoolisé • Choix",
        
        // Ingredients
        "Vodka": "Vodka",
        "Banana": "Banane",
        "Strawberries": "Fraises",
        "Piña Colada": "Piña Colada",
        "Ice": "Glace",
        "Pineapple Juice": "Jus d'ananas",
        "Blue Curaçao": "Curaçao bleu",
        "Ginger Ale": "Ginger ale",
        "Malibu": "Malibu",
        "Orange Juice": "Jus d'orange",
        "Strawberry Fanta": "Fanta fraise",
        "Mango Juice": "Jus de mangue",
        "Guava Juice": "Jus de goyave",
        "Fresh Lime Juice": "Jus de citron vert frais",
        "Green Apple": "Pomme verte",
        "Apple Juice": "Jus de pomme",
        "Grape Juice": "Jus de raisin",
        "Blueberry Juice": "Jus de myrtille",
        "Cranberry Juice": "Jus de canneberge",
        "Watermelon Mojito (can)": "Mojito pastèque (boîte)",
        "Piña Colada (can)": "Piña Colada (boîte)",
        "Tequila": "Tequila",
        "Triple Sec": "Triple sec",
        "Agave Syrup": "Sirop d'agave",
        "Salt": "Sel",
        "White or Dark Rum": "Rhum blanc ou foncé",
        "Coca-Cola": "Coca-Cola",
        "Lime": "Citron vert",
        "Light Beer": "Bière blonde",
        "Rum": "Rhum",
        "Tomato Juice": "Jus de tomate",
        "Lemon Juice": "Jus de citron",
        "Salt & Pepper": "Sel et poivre",
        "Coffee": "Café",
        "Sugar": "Sucre",
        "Milk": "Lait",
        "Tea Bag": "Sachet de thé",
        "Hot Water": "Eau chaude",
        "Sugar or Honey": "Sucre ou miel",
        "Available Juices": "Jus disponibles",
        
        // Amount descriptions
        "1 whole": "1 entier",
        "100g": "100g",
        "150ml": "150ml",
        "1 cup": "1 tasse",
        "120ml": "120ml",
        "20ml": "20ml",
        "Optional top": "Optionnel",
        "Top up": "Compléter",
        "80ml": "80ml",
        "1/2, muddled": "1/2, écrasé",
        "Splash": "Éclaboussure",
        "50ml": "50ml",
        "25ml": "25ml",
        "15ml": "15ml",
        "For rim": "Pour le bord",
        "1 wedge (optional)": "1 quartier (optionnel)",
        "250ml": "250ml",
        "30ml": "30ml",
        "60ml": "60ml",
        "10ml": "10ml",
        "Pinch": "Pincée",
        "1 cup": "1 tasse",
        "Optional": "Optionnel",
        "": "Choix",
        
        // Order Section
        orderTitle: "Commandez Votre Cocktail",
        yourName: "Votre Nom",
        namePlaceholder: "Entrez votre nom",
        chooseDrink: "Choisissez Votre Boisson",
        selectCocktail: "Sélectionnez un cocktail",
        extraIngredients: "Ingrédients Supplémentaires",
        extraAlcohol: "Plus d'alcool",
        moreIce: "Plus de glace",
        lessSugar: "Moins de sucre",
        extraGarnish: "Garniture supplémentaire",
        makeSpicy: "Rendre épicé",
        specialInstructions: "Instructions Spéciales",
        instructionsPlaceholder: "Demandes spéciales ou allergies?",
        placeOrder: "Passer la Commande",
        yourOrder: "Votre Commande",
        previewPlaceholder: "Sélectionnez une boisson pour voir l'aperçu",
        
        // Order Preview
        previewName: "Nom:",
        previewDrink: "Boisson:",
        previewExtras: "Suppléments:",
        previewNotes: "Notes:",
        guest: "Invité",
        
        // Admin Access
        barManager: "Gérant du Bar",
        adminText: "Accédez au panneau d'administration pour voir toutes les commandes",
        goToAdmin: "Aller au Panneau Admin",
        adminNote: "Mot de passe administrateur requis",
        
        // Success Modal
        orderSent: "Commande Envoyée!",
        successMessage: "Votre demande de cocktail a été envoyée au gérant du bar.",
        continue: "Continuer",
        
        // Footer
        copyright: "© 2026 Bar à Cocktails Maison",
        responsible: "Pour usage domestique seulement. Buvez avec modération.",
        
        // Language Switcher
        language: "Langue",
        english: "Anglais",
        russian: "Russe",
        french: "Français",
        selectLanguage: "Choisir la Langue"
    }
};
